name: Deploy to Firebase Hosting
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Este paso crea el archivo JS usando el secreto de GitHub
      - name: Create Firebase Config File
        run: |
          echo "import { initializeApp } from 'https://www.gstatic.com/firebasejs/10.8.0/firebase-app.js';" > firebase-config.js
          echo "import { getAnalytics } from 'https://www.gstatic.com/firebasejs/10.8.0/firebase-analytics.js';" >> firebase-config.js
          echo "${{ secrets.FIREBASE_CONFIG_JS }}" >> firebase-config.js
          echo "const app = initializeApp(firebaseConfig);" >> firebase-config.js
          echo "const analytics = getAnalytics(app);" >> firebase-config.js
          echo "console.log('Tarragona RP: Firebase Cargado.');" >> firebase-config.js

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TARRAGOZA }}'
          channelId: live
          projectId: tarragoza
